# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/testnbdev',
                'doc_host': 'https://jvanelteren.github.io',
                'git_url': 'https://github.com/jvanelteren/testnbdev',
                'lib_path': 'testnbdev'},
  'syms': {'testnbdev\\core': {'testnbdev\\core.foo': ('core.html#foo', 'testnbdev\\core.py')}}}